default:
    dataDirectory: "./data"
    
    backgroundPfamRateFile: "backgroundPFAMRate.txt"
    pfamInfoFile: "pfamInfo.txt"
    metagenomeInfoFile: "metagenomeInfo.txt"
    studyNamesFile: "studyNamesByTaxonOID.csv"
    hmmSummaryFileF: "shortSummariesCombinedPerHMM/hmm.%s.csv"

    brewerColorPalette: "RdYlBu"
    
    mapURL: "https://enzyme.shinyapps.io/Imagenit_map/Imagenit_map"

    sourceHtmlR: "./sourceHtml.R"
