default:
    dataDirectory: "./data"
    metagenomeDataFileNameF: "metagenomeSummaries/taxon%s.csv"
    sfldFamilyDataFile: "SFLDFamilyDataLong.txt"
    sfldSubgroupDataFile: "SFLDSubgroupDataLong.txt"
    
    metagenomeInfoFile: "metagenomeInfo.txt"
    metadataFile: "dereplicated_metagenomes_10_01_2017.edits1.tab"
    pfamInfoFile: "pfamInfo.txt"
    
    sfldSubgroupNameFile: "subgroupNames.txt"
    sfldFamilyNameFile: "familyNames.txt"
    
    brewerColorPalette: "RdYlBu"
    
    
    sourceHtmlR: "./sourceHtml.R"
    
    mapURL: "/map"
    
    
